export * from './cce11/comercio-exterior';
export * from './cce11/descripciones-especificas';
export * from './cce11/destinatario';
export * from './cce11/domicilio';
export * from './cce11/emisor';
export * from './cce11/mercancia';
export * from './cce11/mercancias';
export * from './cce11/propietario';
export * from './cce11/receptor';
